# Generated by Django 2.2.7 on 2019-11-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Users',
        ),
    ]
