# Generated by Django 2.2.7 on 2019-11-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0002_auto_20191119_0653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
