# Generated by Django 2.2.7 on 2019-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0003_auto_20191120_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackdetails',
            fields=[
                ('trackName', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('trackPath', models.CharField(max_length=256, unique=True)),
                ('artworkPath', models.CharField(max_length=256, unique=True)),
                ('artistName', models.CharField(max_length=64)),
            ],
        ),
    ]
