# Generated by Django 2.2.7 on 2019-11-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0004_trackdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackdetails',
            name='songId',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackdetails',
            name='trackName',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
