# Generated by Django 2.2.7 on 2019-11-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0005_auto_20191125_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trackdetails',
            new_name='Trackdetail',
        ),
    ]
