# Generated by Django 2.2.7 on 2019-11-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0006_auto_20191125_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trackdetail',
        ),
    ]
