# Generated by Django 2.2.7 on 2019-11-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0008_trackdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trackdetail',
        ),
    ]
