# Generated by Django 2.2.7 on 2019-11-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0010_trackdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trackdetail',
            new_name='Trackdetails',
        ),
    ]
