# Generated by Django 2.2.7 on 2019-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0012_auto_20191125_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songdetail',
            fields=[
                ('songId', models.AutoField(primary_key=True, serialize=False)),
                ('songName', models.CharField(max_length=64, unique=True)),
                ('songPath', models.CharField(max_length=256, unique=True)),
                ('artworkPath', models.CharField(max_length=256, unique=True)),
                ('artistName', models.CharField(max_length=64)),
            ],
        ),
    ]
