# Generated by Django 2.2.7 on 2019-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeMusicPlayer', '0013_songdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdetail',
            name='artworkPath',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='songdetail',
            name='songPath',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
